import type {ReviewCase} from '../types';
import FootprintProvenance from './FootprintProvenance';
const value=(v:unknown)=>v==null||v===''?'Not supplied':typeof v==='object'?JSON.stringify(v):String(v);
export default function ReviewEvidenceStory({item}:{item:ReviewCase}){
 const p=item.feature.properties,e=p.confidence_explanation,g=p.geometry_quality;
 return <div className="review-evidence-story">
  <section><h3>Cadastral evidence</h3><dl><dt>Survey number</dt><dd>{value(p.cadastral.survey_no)}</dd><dt>Owner / source attribute</dt><dd>{value(p.cadastral.owner)}</dd><dt>{p.cadastral.area_sqm!=null?'Declared area (m²)':'Declared area (source value)'}</dt><dd>{value(p.cadastral.area_sqm??p.cadastral.area??p.attribute_evidence.area?.source)}</dd><dt>Source</dt><dd>{value(p.cadastral.source)}</dd><dt>Geometry</dt><dd>{item.feature.geometry.type} · {g.original_valid?'Valid source':'Invalid source'} → {g.repaired?'Repaired':'Checked'} → {g.result_valid?'Valid':'Invalid'}</dd><dt>Geometry validation detail</dt><dd>{value(g.reason)}</dd></dl></section>
  <section><h3>Drone / building evidence</h3><dl><dt>Candidate footprint</dt><dd>{p.matched_footprint_id||'No candidate'}</dd><dt>Spatial overlap (IoU)</dt><dd>{p.geometry_overlap_pct}%</dd><dt>Source</dt><dd>{value(p.footprint_properties?.source??p.footprint_properties?.source_type)}</dd><dt>Candidate source quality</dt><dd>{value(p.footprint_properties?.quality)}</dd></dl><FootprintProvenance properties={p.footprint_properties}/></section>
  <section><h3>GNSS evidence</h3><dl><dt>Observation</dt><dd>{p.gnss_point_id||'No contained observation returned'}</dd><dt>Containment</dt><dd>{p.gnss_verified?'Contained point':'No containment verified'}</dd><dt>Survey consistency</dt><dd>{p.validation.gnss_related_survey_matches===true?'Survey identifiers agree':p.validation.gnss_related_survey_matches===false?'Survey identifiers disagree':'Not supplied'}</dd></dl></section>
  <section><h3>ML evidence</h3><dl><dt>Model</dt><dd>{p.model_available?value(p.model_version):'Unavailable for this run'}</dd><dt>ML-ranked candidate</dt><dd>{value(p.ml_ranked_candidate_id)}</dd><dt>ML rank</dt><dd>{value(p.ml_rank)}</dd><dt>Model probability</dt><dd>{p.ml_match_probability!=null?`${(p.ml_match_probability*100).toFixed(1)}%`:'Not available'}</dd></dl><p>Candidate ranking trained on synthetic pairs. Model probability is distinct from deterministic confidence.</p></section>
  <section><h3>Deterministic evidence</h3><dl><dt>Geometry contribution</dt><dd>{e.geometry_contribution}</dd><dt>Attribute contribution</dt><dd>{e.attribute_contribution}</dd><dt>GNSS containment boost</dt><dd>{e.gnss_boost}</dd><dt>Final deterministic confidence</dt><dd>{e.final_confidence} / 100</dd></dl><details><summary>Compare source attributes</summary>{Object.entries(p.attribute_evidence).map(([name,v])=><p key={name}><b>{name.replaceAll('_',' ')}</b>: {value(v.source)} → {value(v.candidate)} · {v.available&&v.similarity_pct!=null?`${v.similarity_pct}% similarity`:'Limited evidence'}</p>)}</details></section>
  <section><h3>Validation</h3>{p.validation_flags.length?<ul className="flags">{p.validation_flags.map(f=><li key={f}>{f}</li>)}</ul>:<p>No validation flags returned.</p>}</section>
  <section className="story-recommendation"><h3>Recommendation</h3><b>{p.recommendation}</b><p>{p.validation_flags.length?'The returned validation flags identify disagreements or missing evidence. Inspect them before accepting correspondence.':p.review_required?'The engine requires human review of this proposal. Compare the returned evidence before deciding.':'The engine proposes this correspondence without review flags; it is not a legal determination.'}</p></section>
 </div>;
}
