import {Link} from 'react-router-dom';
import {ArrowRight,ArrowUpRight,Database,Layers,MapPin,Play,CheckCircle2,AlertTriangle,ScanLine,Clock3} from 'lucide-react';
import type {Source,Run,Layers as MapLayers,Results} from '../types';
import Workflow from '../components/Workflow';
import MapView from '../components/MapView';
export default function Dashboard({sources,run,layers,results,running,onRun}:{sources:Source[];run:Run|null;layers:MapLayers|null;results:Results;running:boolean;onRun:()=>void}){
 const icons={cadastral:Database,buildings:Layers,gnss:MapPin};
 const names={cadastral:'Cadastral parcels',buildings:'Building footprints',gnss:'GNSS observations'};
 const summary=results.summary;
 return <><section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="live-dot"/> EXPLAINABLE GEOSPATIAL RECONCILIATION ENGINE</span><h1>Bring clarity to<br/>fragmented land records.</h1><p>Bring fragmented land datasets together, identify corresponding records, explain conflicts, and route uncertain cases for human review.</p><div className="hero-actions"><button className="primary" onClick={onRun} disabled={running||!sources.length}><Play size={16} fill="currentColor"/>{running?'Processing real data…':'Run harmonization'}<ArrowRight size={17}/></button><Link className="text-link" to="/data-sources">Explore data sources <ArrowUpRight size={15}/></Link></div><div className="hero-note"><CheckCircle2 size={14}/> Explainable rules <span>·</span> Visible evidence <span>·</span> Human oversight</div></div><div className="hero-diagram" aria-label="Three data sources connecting to one evidence record"><div className="diagram-grid"/><span className="diagram-caption">MULTIPLE SOURCES. ONE EXPLAINED RESULT.</span><div className="diagram-sources"><span><Database/>Revenue records</span><span><Layers/>Building footprints</span><span><MapPin/>Survey observations</span></div><div className="diagram-connectors"><i/><i/><i/></div><div className="diagram-engine"><span className="engine-mark"><ScanLine size={24}/></span><div><b>BHUMI-SETU</b><small>Normalize · Compare · Explain</small></div><CheckCircle2 size={22}/></div><div className="diagram-result"><span className="live-dot"/>Evidence-backed match proposal<ArrowRight size={14}/></div></div></section>
 <div className="section-top inventory-heading"><div><span className="eyebrow">YOUR CURRENT DEMO DATA</span><h2>Three perspectives on the same place</h2></div><Link className="text-link" to="/data-sources">View sources <ArrowRight size={15}/></Link></div>
 <div className="inventory-grid">{(['cadastral','buildings','gnss'] as const).map(kind=>{const s=sources.find(x=>x.id===kind);const Icon=icons[kind];return <Link to="/data-sources" className="inventory-card" key={kind}><span className={`source-icon ${kind}`}><Icon size={22}/></span><div><span>{names[kind]}</span><strong>{s?s.feature_count.toLocaleString():'—'} <small>features</small></strong></div><div className="inventory-meta"><span className="ready-dot"/> {s?'Ready':'Loading'}<small>{s?.source_crs||'Awaiting backend'}</small></div></Link>})}</div>
 <Workflow completed={!!summary} running={running}/>
 <div className="dashboard-bottom"><section className="panel outcome-panel"><div className="section-top"><div><span className="eyebrow">RECONCILIATION OUTPUT</span><h2>{summary?'Latest run, explained':'Ready for the first comparison'}</h2></div>{run&&<span className="run-duration"><Clock3 size={13}/>{run.duration_seconds}s</span>}</div><div className="outcome-grid">{([{key:'matched',label:'Matched',icon:CheckCircle2},{key:'needs_review',label:'Needs review',icon:Clock3},{key:'conflict',label:'Conflict',icon:AlertTriangle}] as const).map(({key,label,icon:Icon})=><div className={`outcome ${key}`} key={key}><Icon size={17}/><strong>{summary?summary[key]:'—'}</strong><span>{label}</span></div>)}</div>{summary?<><p className="output-note">{summary.total_parcels} parcels compared. {summary.review_required} proposals require review, including high scores with validation flags.</p><div className="run-stamp">Saved {run?.completed_at?new Date(run.completed_at).toLocaleString():''}<Link to="/harmonization">Run details <ArrowRight size={13}/></Link></div></>:<p className="output-note">Run harmonization to calculate these results from the source data. No prefilled scores or simulated progress.</p>}</section><section className="panel map-preview"><div className="section-top"><div><span className="eyebrow">PUNE · MAHARASHTRA</span><h2>The spatial picture</h2></div><Link to="/map" className="square-link" aria-label="Open WebGIS"><ArrowUpRight size={20}/></Link></div><div className="preview-map">{layers?<MapView layers={layers} results={results} visible={{cadastral:true,buildings:true,gnss:true,results:true}} selected={null} onSelect={()=>{}}/>:<div className="empty">Loading geospatial layers…</div>}<Link to="/map" className="map-open">Open WebGIS workspace <ArrowRight size={15}/></Link></div><div className="preview-foot">Synthetic study area <span>Actual backend GeoJSON</span></div></section></div>
 </>;
}
