import {Database,Layers,MapPin,ArrowUpRight,CheckCircle2} from 'lucide-react';
import type {Source} from '../types';
export default function DataSources({sources,onImport,importing}:{sources:Source[];onImport:()=>void;importing:boolean}){
 const icons={cadastral:Database,buildings:Layers,gnss:MapPin};
 return <><div className="page-heading"><div><span className="eyebrow">01 / SOURCE INVENTORY</span><h1>Different sources. Shared geography.</h1><p>Inspect what each dataset contributes before bringing the records together.</p></div><span className="tag"><CheckCircle2 size={14}/> {sources.length} sources available</span></div>
 <div className="notice">Synthetic demonstration dataset · Geography and records are generated near Pune, Maharashtra. These are not government land records or extracted drone observations.</div>
 <section className="panel"><h2>Staged drone building source</h2><p>Six synthetic footprints exercise the AI-derived source contract. No live orthophoto inference. No extraction model, imagery, or fabricated segmentation probability.</p><button className="primary" onClick={onImport} disabled={importing}>{importing?'Importing?':'Import staged drone fixture'}</button><p className="muted">After importing, select the source on Harmonization and run the existing comparison workflow.</p></section>
 <div className="source-grid">{sources.map(s=>{const Icon=icons[s.kind];return <article className="source-card" key={s.id}><div className="section-top"><span className={`source-icon ${s.kind}`}><Icon size={23}/></span><span className="status matched">Available now</span></div><h2>{s.name}</h2>{s.source_type&&<p className="notice">AI-derived drone footprint contract ? {s.label}</p>}<p className="source-count">{s.feature_count.toLocaleString()} <small>features</small></p><div className="source-metadata"><div><span>Source coordinates</span><b>{s.source_crs}</b></div><div><span>Analysis coordinates</span><b>{s.analysis_crs}</b></div><div><span>Map coordinates</span><b>{s.display_crs}</b></div><div><span>Processing</span><b>Normalized & validated</b></div></div><h3>Available fields</h3><div className="field-chips">{s.fields.map(f=><code key={f}>{f}</code>)}</div><h3>Measured quality</h3><div className="quality-pairs"><div><b>{s.quality.invalid_geometries}</b><span>invalid at source</span></div><div><b>{s.quality.repaired_geometries}</b><span>repaired</span></div><div><b>{s.quality.records_missing_attributes}</b><span>limited attributes</span></div><div><b>{s.quality.duplicate_survey_records}</b><span>duplicate survey records</span></div></div><div className="card-foot"><CheckCircle2 size={14}/>{s.quality.valid_after_processing} valid after processing</div></article>})}</div>
 <section className="panel source-explanation"><div><span className="eyebrow">ACTUAL COORDINATE TRANSFORMATION</span><h2>A common reference, with provenance</h2><p>Parcels start in WGS84. Standard footprints and survey points start in UTM 43N; the staged drone fixture starts in EPSG:3857. The backend transforms features into EPSG:32643 for spatial comparison and EPSG:4326 for the map. Original geometry and repair evidence are retained.</p></div><div className="crs-diagram"><span>WGS84 / EPSG:4326</span><ArrowUpRight/><b>UTM 43N / EPSG:32643</b><small>Metric comparison space</small></div></section>
 <section className="panel"><div className="section-top"><h2>More sources, in future phases</h2><span className="muted">Not connected</span></div><div className="planned-sources">{['Municipal GIS','Utilities','Additional revenue sources','Additional drone / ORI','Other survey layers'].map(s=><span key={s}>{s}<small>Planned</small></span>)}</div></section></>;
}
