import {useState} from 'react';
import {SlidersHorizontal,MousePointer2} from 'lucide-react';
import type {Layers,Results,ResultFeature} from '../types';
import MapView from '../components/MapView';
import EvidencePanel from '../components/EvidencePanel';
export default function Workspace({layers,results}:{layers:Layers|null;results:Results}){
 const [visible,setVisible]=useState({cadastral:true,buildings:true,gnss:true,results:true});
 const [selected,setSelected]=useState<ResultFeature|null>(null);
 const [filter,setFilter]=useState('all');const [basemap,setBasemap]=useState(false);
 const filtered={...results,features:results.features.filter(f=>filter==='all'||f.properties.status===filter)};
 return <><div className="page-heading compact"><div><span className="eyebrow">SPATIAL WORKSPACE</span><h1>See the evidence on the ground.</h1><p>Synthetic Pune study area · Select a result parcel to inspect its match.</p></div><label className="select-label">Result filter<select value={filter} onChange={e=>{setFilter(e.target.value);setSelected(null);}}><option value="all">All results</option><option value="matched">Matched</option><option value="needs_review">Needs review</option><option value="conflict">Conflict</option></select></label></div>
 <div className={`gis-layout ${selected?'has-evidence':''}`}><section className="map-panel"><div className="map-toolbar"><span><SlidersHorizontal size={15}/> Layers</span>{Object.entries(visible).map(([k,v])=><label key={k}><input type="checkbox" checked={v} onChange={()=>setVisible({...visible,[k]:!v})}/>{k==='results'?'Results':k==='gnss'?'GNSS':k[0].toUpperCase()+k.slice(1)}</label>)}<label><input type="checkbox" checked={basemap} onChange={()=>setBasemap(!basemap)}/>Street basemap</label></div><div className="workspace-map">{layers?<MapView layers={layers} results={filtered} visible={visible} onSelect={setSelected} selected={selected} basemap={basemap}/>:<div className="empty">Loading map layers…</div>}<div className="map-caption">SYNTHETIC STUDY AREA <span>WGS84 · EPSG:4326</span></div></div><div className="map-bottom"><span><MousePointer2 size={14}/> {results.features.length?'Click a colored parcel for evidence':'Run harmonization to see scored proposals'}</span><div className="legend"><span className="matched">Matched</span><span className="needs_review">Review</span><span className="conflict">Conflict</span></div></div></section>{selected&&<EvidencePanel feature={selected} onClose={()=>setSelected(null)}/>}</div>
 <div className="planned-map-layers">{['Municipal GIS','Utilities','Drone / ORI imagery'].map(label=><label key={label}><input type="checkbox" disabled/>{label} · Planned</label>)}</div>
 {!selected&&results.features.length>0&&<section className="panel"><div className="section-top"><h2>Inspect a record</h2><span className="muted">{filtered.features.length} results in current filter</span></div><div className="record-list">{filtered.features.slice(0,20).map(f=><button onClick={()=>setSelected(f)} key={f.properties.parcel_id}><b>{f.properties.parcel_id}</b><span className={`status ${f.properties.status}`}>{f.properties.confidence}%</span><small>{f.properties.validation_flags[0]||'No validation flags'}</small></button>)}</div></section>}</>;
}
