import {useEffect,useState} from 'react';
import {NavLink,Route,Routes,Link,useLocation} from 'react-router-dom';
import {LayoutDashboard,Database,GitMerge,Map,ClipboardCheck,ShieldCheck,History,Menu,X,ArrowUpRight,Play,CheckCircle2,AlertCircle,RefreshCw} from 'lucide-react';
import type {Health,Source,Run,Results,Layers} from './types';
import {api} from './services/api';
import Dashboard from './pages/Dashboard';
import DataSources from './pages/DataSources';
import Workspace from './pages/Workspace';
import Workflow from './components/Workflow';
import ReviewQueue from './components/ReviewQueue';
import AuditTrail from './pages/AuditTrail';

const empty:Results={type:'FeatureCollection',features:[],summary:null,run_id:null};
const nav=[{to:'/',label:'Overview',icon:LayoutDashboard},{to:'/data-sources',label:'Data sources',icon:Database},{to:'/harmonization',label:'Harmonization',icon:GitMerge},{to:'/map',label:'WebGIS workspace',icon:Map},{to:'/review',label:'Review queue',icon:ClipboardCheck},{to:'/audit',label:'Audit trail',icon:History}];
export default function App(){
 const [health,setHealth]=useState<Health|null>(null),[sources,setSources]=useState<Source[]>([]),[runs,setRuns]=useState<Run[]>([]),[results,setResults]=useState<Results>(empty),[layers,setLayers]=useState<Layers|null>(null),[error,setError]=useState(''),[running,setRunning]=useState(false),[menu,setMenu]=useState(false);
 const location=useLocation();
 const refresh=async()=>{try{await Promise.all([api.health().then(setHealth),api.sources().then(setSources),api.runs().then(setRuns),api.results().then(setResults),api.layers().then(setLayers)]);setError('');}catch(e){setError((e as Error).message||'Unable to connect to backend');}};
 useEffect(()=>{void refresh();},[]);
 useEffect(()=>{setMenu(false);},[location.pathname]);
 const run=async()=>{setRunning(true);setError('');try{await api.run();await refresh();}catch(e){setError((e as Error).message);}finally{setRunning(false);}};
 const latest=runs.find(r=>r.id===results.run_id)||null;
 const page=nav.find(n=>n.to===location.pathname)?.label||'Page not found';
 return <div className="app-shell"><button className="mobile-menu" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>{menu&&<button className="nav-backdrop" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}<aside className={`sidebar ${menu?'open':''}`}><Link to="/" className="brand"><span className="brand-symbol"><i/><i/><i/></span><span>BHUMI-SETU<small>LAND DATA. CONNECTED.</small></span></Link><div className="workspace-label">RECONCILIATION WORKSPACE</div><nav>{nav.slice(0,4).map(({to,label,icon:Icon})=><NavLink to={to} end={to==='/'} key={to}><Icon size={18}/>{label}</NavLink>)}</nav><div className="workspace-label future-label">HUMAN OVERSIGHT</div><div className="disabled-nav">{nav.slice(4).map(({to,label,icon:Icon})=><NavLink to={to} end key={to}><Icon size={18}/><span>{label}</span></NavLink>)}<div><ShieldCheck size={18}/><span>Data quality</span><small>05</small></div></div><div className="sidebar-bottom"><div className="study-card"><span className="live-dot"/><b>Pune study area</b><small>Synthetic demonstration dataset</small><span className="study-tag">PHASE 4 · REVIEW</span></div><p>SIH 2026 <span>/ SIH26013</span></p></div></aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span><b>{page}</b></div><div className="topbar-right"><span className="synthetic-chip">SYNTHETIC DEMONSTRATION</span><span className="connection"><span className={health?'ready-dot':'offline-dot'}/>{health?(health.postgis_connected?'PostGIS connected':'Local demo storage'):'Connecting'}</span><span className="avatar" aria-label="Demo officer">DO</span></div></header><main className="page-content">
 {error&&<div className="error-banner" role="alert"><AlertCircle size={18}/><span>{error}. Check that the MVP backend is available.</span><button onClick={()=>void refresh()}><RefreshCw size={14}/>Retry</button></div>}
 <Routes><Route path="/" element={<Dashboard sources={sources} run={latest} layers={layers} results={results} running={running} onRun={()=>void run()}/>}/><Route path="/data-sources" element={<DataSources sources={sources}/>}/><Route path="/map" element={<Workspace layers={layers} results={results}/>}/><Route path="/review" element={<><div className="page-heading"><div><span className="eyebrow">04 / HUMAN OVERSIGHT</span><h1>Review uncertain cases.</h1><p>Every decision is sent to the backend, version checked, and recorded in the audit trail.</p></div><span className="tag"><ShieldCheck size={14}/> Backend persisted</span></div><ReviewQueue runId={results.run_id}/></>}/><Route path="/audit" element={<AuditTrail runId={results.run_id}/>}/><Route path="/harmonization" element={<><div className="page-heading"><div><span className="eyebrow">02 / RECONCILIATION ENGINE</span><h1>Every score has a reason.</h1><p>Compare the three demonstration sources with explainable rules and preserved evidence.</p></div><button className="primary" disabled={running||!sources.length} onClick={()=>void run()}><Play size={15}/>{running?'Processing real data…':'Run harmonization'}</button></div><Workflow completed={!!latest} running={running}/><div className="panel formula-panel"><div><span className="eyebrow">SCORING POLICY</span><h2>65% geometry + 35% attributes</h2><p>GNSS containment adds up to 8 points, capped at 100. A confidence score is a weighted evidence score, not a calibrated probability.</p><div className="thresholds"><span className="status matched">≥ 75 Matched</span><span className="status needs_review">40–74.9 Needs review</span><span className="status conflict">&lt; 40 Conflict</span></div></div><Link to="/map" className="text-link">Inspect result evidence <ArrowUpRight size={17}/></Link></div><section className="panel"><div className="section-top"><h2>Saved runs</h2><span className="muted">{runs.length} runs</span></div>{runs.length?<div className="run-list">{runs.map(r=><div key={r.id}><CheckCircle2 size={18}/><div><b>{new Date(r.started_at).toLocaleString()}</b><small>{r.id.slice(0,8)} · {r.status}</small></div><span>{r.summary?.total_parcels??'—'} parcels</span><span>{r.duration_seconds??'—'}s</span></div>)}</div>:<p className="muted">No runs yet. Start harmonization to create a saved comparison.</p>}</section></>}/><Route path="*" element={<div className="panel"><h1>Page not found</h1><Link to="/">Return to Overview</Link></div>}/></Routes>
 <footer className="page-footer"><span>BHUMI-SETU <span>Explainable Geospatial Reconciliation Engine</span></span><span>SIH26013 · Phase 3</span></footer></main></div></div>;
}
